from __future__ import annotations

from collections import defaultdict
from datetime import datetime
import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from qportfolio.data.schemas import Asset, MarketSnapshot, PortfolioDataset


class GoIngestAsset(BaseModel):
    """Asset entry emitted by the Go ingestion layer."""

    model_config = ConfigDict(extra="ignore")

    symbol: str
    provider: str | None = None
    vs_currency: str | None = Field(default=None, alias="vs_currency")


class GoIngestOHLCVRecord(BaseModel):
    """Single OHLCV record emitted by the Go ingestion layer."""

    model_config = ConfigDict(extra="ignore")

    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    market_cap: float = Field(default=0.0, alias="market_cap")


class GoIngestPortfolioDataset(BaseModel):
    """Top-level JSON payload emitted by the Go ingestion command."""

    model_config = ConfigDict(extra="ignore")

    provider: str
    vs_currency: str = Field(alias="vs_currency")
    days: int
    assets: list[GoIngestAsset]
    records: list[GoIngestOHLCVRecord]


def load_go_portfolio_dataset(
    path: str | Path,
    *,
    require_complete_snapshots: bool = True,
) -> PortfolioDataset:
    """
    Load and convert the JSON generated by the Go ingestion pipeline.

    Parameters
    ----------
    path:
        Path to the JSON file produced by `go run ./cmd/ingest ...`.
    require_complete_snapshots:
        When True, only timestamps that contain data for every declared asset are
        kept. This is usually the safest default for downstream return/covariance
        calculations.
    """

    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    return parse_go_portfolio_dataset(
        payload,
        require_complete_snapshots=require_complete_snapshots,
    )


def parse_go_portfolio_dataset(
    payload: dict[str, Any],
    *,
    require_complete_snapshots: bool = True,
) -> PortfolioDataset:
    """
    Parse a raw Go-ingestion payload into the Python `PortfolioDataset` schema.
    """

    source = GoIngestPortfolioDataset.model_validate(payload)

    asset_symbols = _ordered_symbols(source)
    if not asset_symbols:
        raise ValueError("Go ingestion payload does not contain any assets.")
    if not source.records:
        raise ValueError("Go ingestion payload does not contain any records.")

    grouped_records = _group_records_by_timestamp(source.records)
    asset_metadata = _build_asset_metadata(asset_symbols, source.records)

    snapshots: list[MarketSnapshot] = []
    for timestamp in sorted(grouped_records.keys()):
        by_symbol = grouped_records[timestamp]
        if require_complete_snapshots and not _has_full_coverage(by_symbol, asset_symbols):
            continue

        prices: dict[str, float] = {}
        volumes: dict[str, float] = {}
        market_caps: dict[str, float] = {}

        for symbol in asset_symbols:
            record = by_symbol.get(symbol)
            if record is None:
                continue
            prices[symbol] = float(record.close)
            volumes[symbol] = float(record.volume)
            market_caps[symbol] = float(record.market_cap)

        if not prices:
            continue

        snapshots.append(
            MarketSnapshot(
                timestamp=timestamp,
                prices=prices,
                volumes=volumes,
                market_caps=market_caps,
            )
        )

    if not snapshots:
        raise ValueError(
            "No valid market snapshots could be built from the Go ingestion payload."
        )

    assets = [
        Asset(
            symbol=symbol,
            name=symbol,
            market_cap=asset_metadata[symbol]["market_cap"],
        )
        for symbol in asset_symbols
    ]

    return PortfolioDataset(assets=assets, snapshots=snapshots)


def _ordered_symbols(source: GoIngestPortfolioDataset) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []

    for asset in source.assets:
        symbol = asset.symbol.upper().strip()
        if symbol and symbol not in seen:
            seen.add(symbol)
            ordered.append(symbol)

    for record in source.records:
        symbol = record.symbol.upper().strip()
        if symbol and symbol not in seen:
            seen.add(symbol)
            ordered.append(symbol)

    return ordered


def _group_records_by_timestamp(
    records: list[GoIngestOHLCVRecord],
) -> dict[str, dict[str, GoIngestOHLCVRecord]]:
    grouped: dict[str, dict[str, GoIngestOHLCVRecord]] = defaultdict(dict)

    for record in records:
        symbol = record.symbol.upper().strip()
        timestamp = _normalize_timestamp(record.timestamp)
        grouped[timestamp][symbol] = record

    return grouped


def _build_asset_metadata(
    asset_symbols: list[str],
    records: list[GoIngestOHLCVRecord],
) -> dict[str, dict[str, float | None]]:
    latest_market_cap: dict[str, tuple[datetime, float]] = {}
    for record in records:
        symbol = record.symbol.upper().strip()
        if symbol not in asset_symbols:
            continue

        previous = latest_market_cap.get(symbol)
        if previous is None or record.timestamp >= previous[0]:
            latest_market_cap[symbol] = (record.timestamp, float(record.market_cap))

    metadata: dict[str, dict[str, float | None]] = {}
    for symbol in asset_symbols:
        market_cap = latest_market_cap.get(symbol, (None, None))[1]
        metadata[symbol] = {"market_cap": market_cap}

    return metadata


def _has_full_coverage(
    by_symbol: dict[str, GoIngestOHLCVRecord],
    asset_symbols: list[str],
) -> bool:
    return all(symbol in by_symbol for symbol in asset_symbols)


def _normalize_timestamp(value: datetime) -> str:
    iso_value = value.isoformat()
    if iso_value.endswith("+00:00"):
        return iso_value.replace("+00:00", "Z")
    return iso_value
